# deploy.yml â€” CI/CD production deploy workflow.
# Project: linkhill
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Hillwork, LLC

name: Production Deployment

on:
  push:
    branches:
      - main  # Only runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: IONOS
    steps:
      - name: Pull latest code on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/link
            git pull origin main
